---

name: RFJ  
about: Describe this issue template's purpose here.  
title: 'RFJ00 - Title'  
labels: ''  
assignees: ''

---

RFJ title: RFJ00

Management: 

Job Owner's GitHub account: 

## Preliminary questions

Write YES or NO to the right of the question:

1. Does this job really need to be done?: 
2. Is this job the best way to achieve the client's goal?: 
3. Are we the most appropriate organization to do the job?: 
4. Would this work contribute to the mission of BDRC?: 
5. Is this job worth doing?: 

If you answered yes for all answers, continue to the request for job (RFJ).

## Request for job

### 1. Summary
_In one or two sentences, describe the new job._

### 2. Background, Need and Objective
_Tell the background story of this project. Explain the reason why this job is really needed and how users will benefit from this job._

### 3. Other options
_Have you considered other ways to solve this problem? Why didn't you choose them?_

### 4. Deliverables
_List the quantifiable, tangible items that this job will produce. Include quantity metrics and descriptions of the quality requirements. Use examples to illustrate the deliverables._

### 5. Constraints
*What constraints—–including deadlines, budget, or other requirements––should PechaJobs consider?*

🕑 Time constraint:  
💵 Budget constraint:  
👌 Quality constraint:  

### 6. Keyword definitions
*Define any new or important concepts used in the summary (section one) or job decription and scope (section three).*

### 7. Unknowns
*What might go wrong and what can BDRC do to reduce those risks? What unanswered questions do you have, if any?*

### 8 Things to do to complete this RFJ
*List anything that the client or job owner needs to do or find out before this RFJ is accepted.*
